/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as CookieRouteImport } from './routes/cookie'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSaved_proposalsRouteImport } from './routes/dashboard/saved_proposals'
import { Route as DashboardSavedRouteImport } from './routes/dashboard/saved'
import { Route as DashboardPricing_engineRouteImport } from './routes/dashboard/pricing_engine'
import { Route as DashboardBrand_syncRouteImport } from './routes/dashboard/brand_sync'
import { Route as DashboardSettingsRouteRouteImport } from './routes/dashboard/settings/route'
import { Route as DashboardWizardIndexRouteImport } from './routes/dashboard/wizard/index'
import { Route as DashboardTemplatesIndexRouteImport } from './routes/dashboard/templates/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardProposalIndexRouteImport } from './routes/dashboard/proposal/index'
import { Route as DashboardTemplatesTnameRouteImport } from './routes/dashboard/templates/$tname'
import { Route as DashboardSettingsSecurityRouteImport } from './routes/dashboard/settings/security'
import { Route as DashboardSettingsProfileRouteImport } from './routes/dashboard/settings/profile'
import { Route as DashboardSettingsPricing_engineRouteImport } from './routes/dashboard/settings/pricing_engine'
import { Route as DashboardSettingsNotificationsRouteImport } from './routes/dashboard/settings/notifications'
import { Route as DashboardSettingsBrandLogosRouteImport } from './routes/dashboard/settings/brand-logos'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieRoute = CookieRouteImport.update({
  id: '/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSaved_proposalsRoute =
  DashboardSaved_proposalsRouteImport.update({
    id: '/saved_proposals',
    path: '/saved_proposals',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSavedRoute = DashboardSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPricing_engineRoute = DashboardPricing_engineRouteImport.update({
  id: '/pricing_engine',
  path: '/pricing_engine',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBrand_syncRoute = DashboardBrand_syncRouteImport.update({
  id: '/brand_sync',
  path: '/brand_sync',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWizardIndexRoute = DashboardWizardIndexRouteImport.update({
  id: '/wizard/',
  path: '/wizard/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTemplatesIndexRoute = DashboardTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const DashboardProposalIndexRoute = DashboardProposalIndexRouteImport.update({
  id: '/proposal/',
  path: '/proposal/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTemplatesTnameRoute = DashboardTemplatesTnameRouteImport.update({
  id: '/templates/$tname',
  path: '/templates/$tname',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsSecurityRoute =
  DashboardSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsProfileRoute =
  DashboardSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsPricing_engineRoute =
  DashboardSettingsPricing_engineRouteImport.update({
    id: '/pricing_engine',
    path: '/pricing_engine',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsNotificationsRoute =
  DashboardSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsBrandLogosRoute =
  DashboardSettingsBrandLogosRouteImport.update({
    id: '/brand-logos',
    path: '/brand-logos',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookie': typeof CookieRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/showcase': typeof ShowcaseRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/dashboard/brand_sync': typeof DashboardBrand_syncRoute
  '/dashboard/pricing_engine': typeof DashboardPricing_engineRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/saved_proposals': typeof DashboardSaved_proposalsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/signup': typeof SignupIndexRoute
  '/dashboard/settings/brand-logos': typeof DashboardSettingsBrandLogosRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/pricing_engine': typeof DashboardSettingsPricing_engineRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/templates/$tname': typeof DashboardTemplatesTnameRoute
  '/dashboard/proposal': typeof DashboardProposalIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/templates': typeof DashboardTemplatesIndexRoute
  '/dashboard/wizard': typeof DashboardWizardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookie': typeof CookieRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/showcase': typeof ShowcaseRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/dashboard/brand_sync': typeof DashboardBrand_syncRoute
  '/dashboard/pricing_engine': typeof DashboardPricing_engineRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/saved_proposals': typeof DashboardSaved_proposalsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/signup': typeof SignupIndexRoute
  '/dashboard/settings/brand-logos': typeof DashboardSettingsBrandLogosRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/pricing_engine': typeof DashboardSettingsPricing_engineRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/templates/$tname': typeof DashboardTemplatesTnameRoute
  '/dashboard/proposal': typeof DashboardProposalIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/templates': typeof DashboardTemplatesIndexRoute
  '/dashboard/wizard': typeof DashboardWizardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookie': typeof CookieRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/showcase': typeof ShowcaseRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/dashboard/brand_sync': typeof DashboardBrand_syncRoute
  '/dashboard/pricing_engine': typeof DashboardPricing_engineRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/saved_proposals': typeof DashboardSaved_proposalsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/dashboard/settings/brand-logos': typeof DashboardSettingsBrandLogosRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/pricing_engine': typeof DashboardSettingsPricing_engineRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/templates/$tname': typeof DashboardTemplatesTnameRoute
  '/dashboard/proposal/': typeof DashboardProposalIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/templates/': typeof DashboardTemplatesIndexRoute
  '/dashboard/wizard/': typeof DashboardWizardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/cookie'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/showcase'
    | '/templates'
    | '/terms'
    | '/dashboard/settings'
    | '/dashboard/brand_sync'
    | '/dashboard/pricing_engine'
    | '/dashboard/saved'
    | '/dashboard/saved_proposals'
    | '/dashboard/'
    | '/login'
    | '/signup'
    | '/dashboard/settings/brand-logos'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/pricing_engine'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/dashboard/templates/$tname'
    | '/dashboard/proposal'
    | '/dashboard/settings/'
    | '/dashboard/templates'
    | '/dashboard/wizard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/cookie'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/showcase'
    | '/templates'
    | '/terms'
    | '/dashboard/brand_sync'
    | '/dashboard/pricing_engine'
    | '/dashboard/saved'
    | '/dashboard/saved_proposals'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/settings/brand-logos'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/pricing_engine'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/dashboard/templates/$tname'
    | '/dashboard/proposal'
    | '/dashboard/settings'
    | '/dashboard/templates'
    | '/dashboard/wizard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/cookie'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/showcase'
    | '/templates'
    | '/terms'
    | '/dashboard/settings'
    | '/dashboard/brand_sync'
    | '/dashboard/pricing_engine'
    | '/dashboard/saved'
    | '/dashboard/saved_proposals'
    | '/dashboard/'
    | '/login/'
    | '/signup/'
    | '/dashboard/settings/brand-logos'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/pricing_engine'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/dashboard/templates/$tname'
    | '/dashboard/proposal/'
    | '/dashboard/settings/'
    | '/dashboard/templates/'
    | '/dashboard/wizard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CookieRoute: typeof CookieRoute
  FeaturesRoute: typeof FeaturesRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ShowcaseRoute: typeof ShowcaseRoute
  TemplatesRoute: typeof TemplatesRoute
  TermsRoute: typeof TermsRoute
  LoginIndexRoute: typeof LoginIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie': {
      id: '/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/saved_proposals': {
      id: '/dashboard/saved_proposals'
      path: '/saved_proposals'
      fullPath: '/dashboard/saved_proposals'
      preLoaderRoute: typeof DashboardSaved_proposalsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/saved': {
      id: '/dashboard/saved'
      path: '/saved'
      fullPath: '/dashboard/saved'
      preLoaderRoute: typeof DashboardSavedRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/pricing_engine': {
      id: '/dashboard/pricing_engine'
      path: '/pricing_engine'
      fullPath: '/dashboard/pricing_engine'
      preLoaderRoute: typeof DashboardPricing_engineRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/brand_sync': {
      id: '/dashboard/brand_sync'
      path: '/brand_sync'
      fullPath: '/dashboard/brand_sync'
      preLoaderRoute: typeof DashboardBrand_syncRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/wizard/': {
      id: '/dashboard/wizard/'
      path: '/wizard'
      fullPath: '/dashboard/wizard'
      preLoaderRoute: typeof DashboardWizardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/templates/': {
      id: '/dashboard/templates/'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/proposal/': {
      id: '/dashboard/proposal/'
      path: '/proposal'
      fullPath: '/dashboard/proposal'
      preLoaderRoute: typeof DashboardProposalIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/templates/$tname': {
      id: '/dashboard/templates/$tname'
      path: '/templates/$tname'
      fullPath: '/dashboard/templates/$tname'
      preLoaderRoute: typeof DashboardTemplatesTnameRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/security': {
      id: '/dashboard/settings/security'
      path: '/security'
      fullPath: '/dashboard/settings/security'
      preLoaderRoute: typeof DashboardSettingsSecurityRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/profile': {
      id: '/dashboard/settings/profile'
      path: '/profile'
      fullPath: '/dashboard/settings/profile'
      preLoaderRoute: typeof DashboardSettingsProfileRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/pricing_engine': {
      id: '/dashboard/settings/pricing_engine'
      path: '/pricing_engine'
      fullPath: '/dashboard/settings/pricing_engine'
      preLoaderRoute: typeof DashboardSettingsPricing_engineRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/notifications': {
      id: '/dashboard/settings/notifications'
      path: '/notifications'
      fullPath: '/dashboard/settings/notifications'
      preLoaderRoute: typeof DashboardSettingsNotificationsRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/brand-logos': {
      id: '/dashboard/settings/brand-logos'
      path: '/brand-logos'
      fullPath: '/dashboard/settings/brand-logos'
      preLoaderRoute: typeof DashboardSettingsBrandLogosRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
  }
}

interface DashboardSettingsRouteRouteChildren {
  DashboardSettingsBrandLogosRoute: typeof DashboardSettingsBrandLogosRoute
  DashboardSettingsNotificationsRoute: typeof DashboardSettingsNotificationsRoute
  DashboardSettingsPricing_engineRoute: typeof DashboardSettingsPricing_engineRoute
  DashboardSettingsProfileRoute: typeof DashboardSettingsProfileRoute
  DashboardSettingsSecurityRoute: typeof DashboardSettingsSecurityRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteRouteChildren: DashboardSettingsRouteRouteChildren =
  {
    DashboardSettingsBrandLogosRoute: DashboardSettingsBrandLogosRoute,
    DashboardSettingsNotificationsRoute: DashboardSettingsNotificationsRoute,
    DashboardSettingsPricing_engineRoute: DashboardSettingsPricing_engineRoute,
    DashboardSettingsProfileRoute: DashboardSettingsProfileRoute,
    DashboardSettingsSecurityRoute: DashboardSettingsSecurityRoute,
    DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  }

const DashboardSettingsRouteRouteWithChildren =
  DashboardSettingsRouteRoute._addFileChildren(
    DashboardSettingsRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRouteWithChildren
  DashboardBrand_syncRoute: typeof DashboardBrand_syncRoute
  DashboardPricing_engineRoute: typeof DashboardPricing_engineRoute
  DashboardSavedRoute: typeof DashboardSavedRoute
  DashboardSaved_proposalsRoute: typeof DashboardSaved_proposalsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardTemplatesTnameRoute: typeof DashboardTemplatesTnameRoute
  DashboardProposalIndexRoute: typeof DashboardProposalIndexRoute
  DashboardTemplatesIndexRoute: typeof DashboardTemplatesIndexRoute
  DashboardWizardIndexRoute: typeof DashboardWizardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardSettingsRouteRoute: DashboardSettingsRouteRouteWithChildren,
  DashboardBrand_syncRoute: DashboardBrand_syncRoute,
  DashboardPricing_engineRoute: DashboardPricing_engineRoute,
  DashboardSavedRoute: DashboardSavedRoute,
  DashboardSaved_proposalsRoute: DashboardSaved_proposalsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardTemplatesTnameRoute: DashboardTemplatesTnameRoute,
  DashboardProposalIndexRoute: DashboardProposalIndexRoute,
  DashboardTemplatesIndexRoute: DashboardTemplatesIndexRoute,
  DashboardWizardIndexRoute: DashboardWizardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CookieRoute: CookieRoute,
  FeaturesRoute: FeaturesRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ShowcaseRoute: ShowcaseRoute,
  TemplatesRoute: TemplatesRoute,
  TermsRoute: TermsRoute,
  LoginIndexRoute: LoginIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
